pipeline {
    agent any

    tools {
        jdk 'jdk17'
        nodejs 'node18.x'
    }

    environment {
        SCANNER_HOME = tool 'sonar-scanner'
        DOCKER_IMAGE = 'arunasri0096/bms:latest'
        AWS_REGION = 'us-east-1'
    }

    stages {

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout from Git') {
            steps {
                git branch: 'main',
                credentialsId: 'git-cred',
                url: 'https://github.com/Arunasri-0096/Book-My-Show.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                rm -rf node_modules package-lock.json
                npm install --legacy-peer-deps
                '''
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonar-server') {
                    sh """
                    $SCANNER_HOME/bin/sonar-scanner \
                    -Dsonar.projectName=BMS \
                    -Dsonar.projectKey=BMS
                    """
                }
            }
        }

        stage('Quality Gate') {
            steps {
                waitForQualityGate abortPipeline: false,
                credentialsId: 'sonar-cred'
            }
        }

        stage('Trivy FS Scan') {
            steps {
                sh 'trivy fs . > trivyfs.txt || true'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE .'
            }
        }

        stage('Docker Login & Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {

                    sh '''
                    echo $PASS | docker login -u $USER --password-stdin
                    docker push $DOCKER_IMAGE
                    '''
                }
            }
        }

        stage('Deploy Container') {
            steps {
                sh '''
                docker stop bms || true
                docker rm bms || true

                docker run -d \
                --name bms \
                --restart=always \
                -p 3000:3000 \
                $DOCKER_IMAGE
                '''
            }
        }
    }

    post {
        always {
            emailext attachLog: true,
            subject: "${currentBuild.result}",
            body: """
            Project: ${env.JOB_NAME}<br/>
            Build: ${env.BUILD_NUMBER}<br/>
            URL: ${env.BUILD_URL}
            """,
            to: 'kastrokiran@gmail.com',
            attachmentsPattern: 'trivyfs.txt'
        }
    }
}
